{-
   The Work Number ID API

   # Introduction The Work Number&reg; ID verifies that the applicant-provided Name and SSN match. By doing so, TWN ID helps mitigate the expense of manual review. Customers use TWN ID during the application process to make prompt, more informed decisions.  # Getting started 1. **<a href=\"/user/user-apps\" target=\"_blank\">Subscribe</a>** to get API credentials. 2. **<a href=\"/oauth\" target=\"_blank\">Get an access token</a>** using the credentials. 3. **[Identity verification](#tag/Identity-verification)** 

   OpenAPI Version: 3.0.0
   The Work Number ID API API version: v1
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : WorkNumberID
-}

module TheEquifax.WorkNumberID
  (  module TheEquifax.WorkNumberID.Model
  ) where

import TheEquifax.WorkNumberID.Model