{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import ConsumerCreditReport.Model
import ConsumerCreditReport.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 10) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy APIErrorResponse)
      propMimeEq MimeJSON (Proxy :: Proxy AccountDesignatorCode)
      propMimeEq MimeJSON (Proxy :: Proxy AccountTypeCode)
      propMimeEq MimeJSON (Proxy :: Proxy AdditionalErrorDetails)
      propMimeEq MimeJSON (Proxy :: Proxy Address)
      propMimeEq MimeJSON (Proxy :: Proxy AddressAddressVarianceIndicator)
      propMimeEq MimeJSON (Proxy :: Proxy AddressRequest)
      propMimeEq MimeJSON (Proxy :: Proxy AddressSourceOfAddress)
      propMimeEq MimeJSON (Proxy :: Proxy AddressSourceOfTelephoneNumber)
      propMimeEq MimeJSON (Proxy :: Proxy AlertContactAddress)
      propMimeEq MimeJSON (Proxy :: Proxy Bankruptcy)
      propMimeEq MimeJSON (Proxy :: Proxy BankruptcyCurrentIntentOrDispositionCode)
      propMimeEq MimeJSON (Proxy :: Proxy BankruptcyPriorIntentOrDispositionCode)
      propMimeEq MimeJSON (Proxy :: Proxy Collection)
      propMimeEq MimeJSON (Proxy :: Proxy CollectionStatusCode)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReport)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAlertContacts)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAlertType)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAlternateDataSources)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAlternateDataSourcesAlternateDataSourceCode)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAlternateDataSourcesAlternateDataSourceErrorMessage)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAlternateDataSourcesErrorCodes)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAlternateDataSourcesFraudIQSyntheticIDAlerts)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAlternateDataSourcesFraudIQSyntheticIDV2Alerts)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAlternateDataSourcesMilitaryLendingCoveredBorrower)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAlternateDataSourcesNorthAmericanLink)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAttributes)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportAttributes1)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportConsumerReferralLocation)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportConsumerReferralLocationAddress)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportConsumerReferralLocationTelephoneNumber)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportConsumerStatements)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportEDASIndicatorCode)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportEDASRegionalIndicatorCode)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportEmployments)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportEquifaxUSConsumerCreditReport)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportFICOScoreIndicatorCode)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportFormerNames)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportFraudSocialNumAlertCode)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportFraudVictimIndicator)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportHitCode)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportIdentification)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportIdentityScan)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportIdentityScanAlertCodes)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportInquiries)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportInquiryKeyFactor)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportModels)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportNameMatchFlags)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportOnlineDirectory)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportOnlineGeoCode)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportOtherIdentification)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportReasonCode)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportReasons)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportRejects)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportReturnCode1)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportReturnCode2)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportReturnCode3)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportReturnCode4)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportRiskBasedPricingOrModel)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportScoreNumberOrMarketMaxIndustryCode)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportSubjectName)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportTelephoneNumberType)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportTelephoneNumbers)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportTypeCode)
      propMimeEq MimeJSON (Proxy :: Proxy ConsumerCreditReportTypeOfAddress)
      propMimeEq MimeJSON (Proxy :: Proxy CreditReportRequest)
      propMimeEq MimeJSON (Proxy :: Proxy CreditReportRequestConsumers)
      propMimeEq MimeJSON (Proxy :: Proxy CreditReportRequestConsumersEmployments)
      propMimeEq MimeJSON (Proxy :: Proxy CreditReportRequestConsumersName)
      propMimeEq MimeJSON (Proxy :: Proxy CreditReportRequestConsumersPhoneNumbers)
      propMimeEq MimeJSON (Proxy :: Proxy CreditReportRequestConsumersSocialNum)
      propMimeEq MimeJSON (Proxy :: Proxy CreditReportRequestCustomerConfiguration)
      propMimeEq MimeJSON (Proxy :: Proxy CreditReportRequestExternalDataSources)
      propMimeEq MimeJSON (Proxy :: Proxy CreditReportRequestExternalDataSourcesAlternateDataSources)
      propMimeEq MimeJSON (Proxy :: Proxy CreditReportResponse)
      propMimeEq MimeJSON (Proxy :: Proxy CreditReportResponseLinks)
      propMimeEq MimeJSON (Proxy :: Proxy CreditorClassificationCode)
      propMimeEq MimeJSON (Proxy :: Proxy EquifaxUSConsumerCreditRequest)
      propMimeEq MimeJSON (Proxy :: Proxy EquifaxUSConsumerCreditRequestEndUserInformation)
      propMimeEq MimeJSON (Proxy :: Proxy EquifaxUSConsumerCreditRequestModels)
      propMimeEq MimeJSON (Proxy :: Proxy EquifaxUSConsumerCreditRequestProductInformation)
      propMimeEq MimeJSON (Proxy :: Proxy EquifaxUSConsumerCreditRequestProductInformationDriverLicenseNumber)
      propMimeEq MimeJSON (Proxy :: Proxy Trade)
      propMimeEq MimeJSON (Proxy :: Proxy Trade24MonthPaymentHistory)
      propMimeEq MimeJSON (Proxy :: Proxy TradeActivityDesignatorCode)
      propMimeEq MimeJSON (Proxy :: Proxy TradeDimension)
      propMimeEq MimeJSON (Proxy :: Proxy TradePaymentHistory1to24)
      propMimeEq MimeJSON (Proxy :: Proxy TradePaymentHistory25to36)
      propMimeEq MimeJSON (Proxy :: Proxy TradePaymentHistory37to48)
      propMimeEq MimeJSON (Proxy :: Proxy TradePortfolioTypeCode)
      propMimeEq MimeJSON (Proxy :: Proxy TradePurchasedFromOrSoldCreditorIndicator)
      propMimeEq MimeJSON (Proxy :: Proxy TradeRate)
      propMimeEq MimeJSON (Proxy :: Proxy TradeRateStatusCode)
      propMimeEq MimeJSON (Proxy :: Proxy TradeTermsDurationCode)
      propMimeEq MimeJSON (Proxy :: Proxy TradeTermsFrequencyCode)
      
